# Generated by Django 3.0.5 on 2020-05-03 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='complaints',
            field=models.TextField(blank=True, verbose_name='Основные жалобы'),
        ),
        migrations.AddField(
            model_name='ward',
            name='doctor_description',
            field=models.TextField(blank=True, verbose_name='Лечащий врач'),
        ),
        migrations.AddField(
            model_name='ward',
            name='middle_name',
            field=models.CharField(default='', max_length=256, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='phone',
            field=models.CharField(default='', max_length=1024, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Персональные рекомендации'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительная информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ward',
            name='disease',
            field=models.ManyToManyField(to='app.Disease', verbose_name='Заболевания'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сиделка'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='status',
            field=models.CharField(choices=[('W', 'Ходячий'), ('S', 'Сидящий'), ('B', 'Лежащий')], default='W', max_length=1, verbose_name='Статус'),
        ),
    ]
